<form class="" action="<?= /* @noEscape */ $block->getBaseUrl().'signup/index/save'; ?>" 
id="bhaveshpp-stagebit-form" method="post" data-mage-init='{"validation": {}}'>
    <fieldset class="fieldset">
        <div class="field name">
            <label class="label" for="name"><span>Name</span></label>
            <div class="control">
                <input name="name" id="name" title="Name" value="" autofocus 
                placeholder="Name" class="input-text" type="text" data-validate="{required:true}">
            </div>
        </div>
        <div class="field date">
            <label class="label" for="date"><span>Date</span></label>
            <div class="control">
                <input name="date" id="date" title="Date" value="" class="input-date" 
                type="date" data-validate="{required:true}">
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="Submit" class="action submit primary">
                <span>Submit</span>
            </button>
        </div>
    </div>
</form>